name: "Main workflow (workflow_run) part2"
on: workflow_dispatch
env:
  HOGE: "hoge"
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Debug
        run: |
          echo "HOGE part2"
