name: "Release test"

on:
  release:
    types:
      - released

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release tag
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
