name: "Sub workflow (workflow_run)"
on:
  workflow_run:
    workflows: ["Main workflow (workflow_run)"]
    types:
      - completed
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Print info
        run: |
          echo "Head commit: ${{ github.event.workflow_run.head_commit }}"
          echo "Head commit ID : ${{ github.event.workflow_run.head_commit.id }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Caller workflow ID: ${{ github.event.workflow_run.workflow_id }}"
          echo "Caller workflow name: ${{ github.event.workflow_run.name }}"
