name: "Sub workflow (workflow_run)"
on:
  workflow_run:
    workflows:
      - '[part1] Main workflow (workflow_run)'
      - '[part2] Main workflow (workflow_run)'
      - '[part3] Main workflow (workflow_run)'
    types:
      - completed
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Select target S3 bucket
        id: select-bucket
        run: |
          case "${{ github.event.workflow_run.name }}" in
            "[part1] Main workflow (workflow_run)")
              echo "bucketname=stg-bucket" >> $GITHUB_OUTPUT
              ;;
            "[part2] Main workflow (workflow_run)")
              echo "bucketname=stg2-bucket" >> $GITHUB_OUTPUT
              ;;
            *)
              exit 1
              ;;
          esac

      - name: Print info
        run: |
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Caller workflow ID: ${{ github.event.workflow_run.workflow_id }}"
          echo "Caller workflow name: ${{ github.event.workflow_run.name }}"
          echo "Caller workflow path: ${{ github.event.workflow_run.path }}"
          echo "Target Bucket: ${{ steps.select-bucket.outputs.bucketname }}"
