name: "Sub workflow (workflow_run)"
on:
  workflow_run:
    workflows:
      - "Main workflow (workflow_run) part1"
      - "Main workflow (workflow_run) part2"
      - "Main workflow (workflow_run) part3"
    types:
      - completed
env:
  WORKFLOW_FROM: |-
    ${{ fromJson('{
      "Main workflow (workflow_run) part1": "From Part1",
      "Main workflow (workflow_run) part2": "From Part2",
      "Main workflow (workflow_run) part3": "From Part3"
      }')[github.event.workflow_run.name] }}jobs:
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Print info
        run: |
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Caller workflow ID: ${{ github.event.workflow_run.workflow_id }}"
          echo "Caller workflow name: ${{ github.event.workflow_run.name }}"
          echo "Caller workflow path: ${{ github.event.workflow_run.path }}"
          echo "WORKFLOW_FROM: ${{ env.WORKFLOW_FROM }}"
