name: "Sub workflow"
on:
  workflow_dispatch:
    inputs:
      foo:
        description: "foo"
        required: true
        default: "bar"
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Sleep
        run: |
          echo "Sleeping..."
          sleep 10
      - name: Dump paylowd
        run: |
          echo "Payload: ${{ inputs.foo }}"
